config/routes.rb
Rails.application.routes.draw do
    
    root               'home#index'
    
    get    'signup' => 'users#new'
    get    'login'  => 'sessions#new'
    post   'login'  => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
    
    get    'cart'           => 'users#shopping_cart', as: :user_cart
    post   'products/:id'   => 'shopping_cart_items#create'
    put    'products/:id'   => 'user_product_favorites#create'
    delete 'products/:id'   => 'user_product_favorites#destroy'
    post   'cart'           => 'shopping_cart_items#update'
    delete 'cart'           => 'shopping_cart_items#destroy'

    resources :products do
        resources :reviews
    end
    
    resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_many :shoppingCartItems, dependent: :destroy
    has_many :userProductFavorites, dependent: :destroy
    
    # Field validations
    validates :username, presence: true
    validates_uniqueness_of :username
    validates :email, presence: true
    validates :password, presence: true, confirmation: true
    # validates :password_confirmation, presence: true
    
    # Default sort by username
    default_scope { order('username ASC') }
    
    def cart_total_price
        @cartItemSum = 0
        self.shoppingCartItems.each do |item|
            @cartItemSum += (item.product.price * item.quantity)
        end
        @cartItemSum
    end
    
    def has_item_in_cart(productId)
        !ShoppingCartItem.where(:user_id => self.id, :product_id => productId).take.nil?
    end
    
    def has_item_favorited(productId)
        !UserProductFavorite.where(:user_id => self.id, :product_id => productId).take.nil?
    end
    
    def favorite_products
        Product.where(id: UserProductFavorite.where(:user_id => self.id).pluck(:product_id))
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def new
        @user = User.new
    end
    
    def edit
        confirm_user
        @user = User.find(params[:id])
    end
    
    def create
        @user = User.new(user_params)
        @user.isAdmin = false
        @user.image = 'no_image.jpg'
        @user.cartSize = 0
        
        if @user.save
            log_in @user
            redirect_to root_path
        else
            flash.now[:danger] = 'All fields are required.  Ensure the password fields match.'
            render 'new'
        end
    end
    
    def update
        confirm_user
        @user = User.find(params[:id])
        
        if @user.update(user_params)
            redirect_to @user
        else
            render 'edit'
        end
    end
    
    def destroy
        confirm_user
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end
    
    #def cart_total_price
    #    User.find(params[:id]).shopping_cart_items.sum(:product.price)
    #end
    
    def confirm_user
        if !logged_in? || (logged_in? && current_user.username != @user.username)
            redirect_to users_path
        end
    end
    
    private
        def user_params
            params.require(:user).permit(:username, :email, :password, :password_confirmation, :isAdmin, :image)
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <div class="user-signup-content well">
        <h1>Create an Account!</h1>
        
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        
        <strong>Username</strong>
        <%= f.text_field :username, class: 'form-control' %>
        
        <strong>Email Address</strong>
        <%= f.text_field :email, class: 'form-control' %>
        
        <strong>Password</strong>
        <%= f.password_field :password, class: 'form-control' %>
        
        <strong>Confirm Password</strong>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        
        <div class="signup-btn-container">
            <%= f.submit "Sign Up", class: 'btn btn-primary' %>
        </div>
        
        <div class="login-link-container">
            <p>Already have an account? <%= link_to "Log in!", login_path %></p>
        </div>
    </div>
<% end %>

app/views/users/_user.html.erb
<tr class="user-row">
    <td class="col-xs-1 user-image">
        <% if !user.image.nil? %>
            <img src="images/users/<%= user.image %>" alt="<%= user.username %>"/>
        <% end %>
    </td> 
    <td class="col-xs-2 user-username"><%= user.username %></td>
    <td class="col-xs-2 user-email"><%= user.email %></td>
    <% if logged_in? && current_user.isAdmin %>
        <td class="col-xs-1 user-admin"><%= user.isAdmin ? 'admin' : '' %></td>
    <% end %>
    <td class="col-xs-1 user-actions"><%= link_to 'View', user_path(user), class: 'btn btn-primary' %></td>
</tr>

app/views/users/edit.html.erb
<%= render 'layouts/navbar' %>
<div class="edit-user-page">
    <h1>Editing User</h1>
    
    <%= form_for @user do |f| %>
    
        <div class="edit-user-content well">
    
            <% if @user.errors.any? %>
                <div id="error_explanation">
                    <ul>
                        <% @user.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
        
            <strong>Username</strong>
            <p><%= @user.username %></p>
            
            <strong>Email</strong>
            <%= f.text_field :email, class: 'form-control' %>
            
            <strong>Image Name</strong>
            <%= f.text_field :image, class: 'form-control' %>
            
            <div class="buttons-container">
                <%= link_to 'Cancel', @user, class: 'btn btn-default' %>
                <%= f.submit 'Save Changes', class: 'btn btn-success' %>
            </div>
        </div>
        
    <% end %>
</div>

app/views/users/index.html.erb
<div class="all-users-page">
    <%= render 'layouts/navbar' %>

    <div class="all-users-content">
        <h2>All Users</h2>
        
        <div class="all-users-table">
            <table class="table table-condensed">
                <tr>
                    <th>Image</th>
                    <th>Username</th>
                    <th>Email</th>
                    <% if logged_in? && current_user.isAdmin %>
                        <th>Admin?</th>
                    <% end %>
                    <th>Actions</th>
                </tr>
                <%= render @users %>
            </table>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="user-signup-page">
    <%= render 'layouts/navbar' %>
    <%= render 'form' %>
</div>

<script>
    $(document).ready(function() {
        $('input#user_username').focus();
    });
</script>

app/views/users/shopping_cart.html.erb
<div class="shopping-cart-page">
    <%= render 'layouts/navbar' %>
    
    <div class="shopping-cart-content">
        <h1>Shopping Cart</h1>
        <hr/>
        
        <% if logged_in? %>
            <!-- Logged in -->
            
            <% if current_user.cartSize > 0 %>
                <!-- Has items in cart -->
                
                <table class="table table-condensed">
                    <tr>
                        <th class="col-sm-5" colspan="3">Product</th>
                        <th class="col-sm-2">Quantity</th>
                        <th class="col-sm-2">Product Price</th>
                        <th class="col-sm-3">Product Sub-Total</th>
                    </tr>
                    
                    <%= render current_user.shoppingCartItems %>
                    
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><strong>Grand Total:</strong></td>
                        <td><strong>$<%= number_with_precision(current_user.cart_total_price, precision: 2) %></strong></td>
                    </tr>
                </table>
            <% else %>
                <!-- No items in cart -->
                <h2>You don't have any items in your cart!</h2>
                <p>Head to the <%= link_to 'products page', products_path %> to find what's perfect for you.</p>
            <% end %>
        <% else %>
            <!-- Not logged in -->
            <h4><%= link_to 'Log in', login_path %> or <%= link_to 'sign up', signup_path %> to get shopping!</h4>
        <% end %>
    </div>
</div>

<script>
    $(document).ready(function() {
        
        // When the quantity is changed in the modal, update the quantity parameter on the 'confirm' link
        $('div.edit-quantity-modal div.modal-body input').change(function() {
            var quantity = Number($(this).val());
            var updateQuantityLink = $(this).closest('div.modal-content').find('div.modal-footer a.btn-update-quantity');
            var linkText = updateQuantityLink.attr('href');
            var startIndex = (linkText.indexOf('&quantity=') + 10);
            var updatedLink = (linkText.substring(0, startIndex) + quantity);
            updateQuantityLink.attr('href', updatedLink);
        });
    });
</script>

app/views/users/show.html.erb
<div class="user-detail-page">
    <%= render 'layouts/navbar' %>
    
    <div class="user-detail-content">
        <div class="user-info">
            <div class="user-image col-sm-3">
                <img src="../images/users/<%= @user.image %>" alt="<%= @user.username %>"/>
            </div>
            <div class="user-details col-sm-9">
                <h2><%= @user.username %> <% if @user.isAdmin %>(admin)<% end %></h2>
                <p>
                    <strong>Email:</strong>
                    <%= @user.email %>
                </p>
                
                <% if logged_in? && (current_user.isAdmin || (current_user.username == @user.username)) %>
                    <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
                    
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete-modal">
                            Delete
                    </button>
                    <div id="delete-modal" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">
                                        <span class="fa fa-close"/>
                                    </button>
                                    <h4 class="modal-title">Delete</h4>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure you want to delete this user? (<%= @user.username %>)</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">
                                        <span class="fa fa-close"/> Cancel
                                    </button>
                                    <%= link_to raw('<div class="btn btn-danger"><span class="fa fa-trash"/> Delete</div>'), user_path(@user), method: :delete %>
                                </div>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
        
        <div class="separator"></div>
        <hr/>
        
        <div class="user-favorite-products">
            <h2>Favorite Products</h2>
            
            <table class="table table-condensed">
                <%= render @user.favorite_products %>
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('tr.product-row').click(function() {
            $(this).next('tr.product-row-detail').find('div').slideToggle(300);
        });
        $('tr.product-row-detail').click(function() {
            $(this).find('div').slideUp(300);
        });
        $('a.btn').click(function(e) {
            e.stopPropagation();
        });
        $('td.product-action-delete button.btn-danger').click(function(e) {
            e.stopPropagation();
            $($(this).attr('data-target')).modal('show');
        });
    });
</script>