config/routes.rb
Rails.application.routes.draw do
    
    root               'home#index'
    
    get    'signup' => 'users#new'
    get    'login'  => 'sessions#new'
    post   'login'  => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
    
    get    'cart'           => 'users#shopping_cart', as: :user_cart
    post   'products/:id'   => 'shopping_cart_items#create'
    put    'products/:id'   => 'user_product_favorites#create'
    delete 'products/:id'   => 'user_product_favorites#destroy'
    post   'cart'           => 'shopping_cart_items#update'
    delete 'cart'           => 'shopping_cart_items#destroy'

    resources :products do
        resources :reviews
    end
    
    resources :users

end

app/models/product.rb
class Product < ActiveRecord::Base
    
    # Model relationships
    has_many :reviews, dependent: :destroy
    has_many :shoppingCartItems, dependent: :destroy
    has_many :userProductFavorites, dependent: :destroy
    
    # Field validations
    validates :name, presence: true
    validates :description, presence: true
    validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    
    # Default sort by name
    default_scope { order('name ASC') }
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    def index
        @products = Product.all
    end
    
    def show
        @product = Product.find(params[:id])
    end
    
    def new
        @product = Product.new
    end
    
    def edit
        confirm_admin
        @product = Product.find(params[:id])
    end
    
    def create
        confirm_admin
        @product = Product.new(product_params)
        @product.isFeatured = false
        if @product.save
            redirect_to @product
        else
            render 'new'
        end
    end
    
    def update
        confirm_admin
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to @product
        else
            render 'edit'
        end
    end
    
    def destroy
        confirm_admin
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to products_path
    end
    
    def confirm_admin
        if !logged_in? || (logged_in? && !current_user.isAdmin)
            redirect_to products_path
        end
    end
    
    private
        def product_params
            params.require(:product).permit(:name, :description, :price, :image, :isFeatured)
        end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
    <div class="well">
        <% if @product.errors.any? %>
            <div id="error_explanation">
                <h2>
                    <%= pluralize(@product.errors.count, "error") %>
                    prohibited this product from being saved:
                </h2>
                <ul>
                    <% @product.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        
        <strong>Name</strong>
        <%= f.text_field :name, class: 'form-control' %>
        
        <strong>Description</strong>
        <%= f.text_area :description, class: 'form-control' %>
        
        <strong>Price (USD)</strong>
        <%= f.number_field :price, class: 'text_field, form-control',
                                   :step => 0.01,
                                   :min => 0.0 %>
        
        <strong>Image Name (e.g. my_product.jpg)</strong>
        <%= f.text_field :image, class: 'form-control' %>
        
        <strong>Featured on Home Page?</strong>
        <%= f.check_box :isFeatured %>
        
        <div class="submit-btn-container">
            <%= link_to 'Cancel', products_path, class: 'btn btn-default' %>
            <%= f.submit class: 'btn btn-success' %>
        </div>
    </div>
<% end %>

app/views/products/_product.html.erb
<tr class="product-row">
    <td class="col-xs-3 product-image"><img src="../images/products/<%= product.image %>" alt="<%= product.name %>"/></td>
    <td class="col-xs-6 product-name"><%= product.name %></td>
    <td class="col-xs-2 product-price"><%= '$' + product.price.to_s %></td>
    <td class="col-xs-1 product-action-view">
        <%= link_to 'View', product_path(product), class: 'btn btn-primary' %>
    </td>
    <% if logged_in? && current_user.isAdmin %>
        <td class="col-xs-1 product-action-edit">
            <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-warning' %>
        </td>
        <td class="col-xs-1 product-action-delete">
            <button type="button" class="btn btn-danger btn-delete-<%= product.id %>"
                    data-toggle="modal" data-target="#delete-modal-<%= product.id %>">
                    Delete
            </button>
        </td>
        <div id="delete-modal-<%= product.id %>" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span class="fa fa-close"/>
                        </button>
                        <h4 class="modal-title">Delete</h4>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this product? (<%= product.name %>)</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <span class="fa fa-close"/> Cancel
                        </button>
                        <%= link_to raw('<div class="btn btn-danger"><span class="fa fa-trash"/> Delete</div>'), product_path(product), method: :delete %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</tr>
<tr class="product-row-detail">
    <td class="col-xs-3"><div></div></td>
    <td class="col-xs-6"><div><%= product.description %></div></td>
    <td class="col-xs-2"><div></div></td>
    <td class="col-xs-1"><div></div></td>
    <% if logged_in? && current_user.isAdmin %>
        <td class="col-xs-1"><div></div></td>
        <td class="col-xs-1"><div></div></td>
    <% end %>
</tr>

app/views/products/edit.html.erb
<%= render 'layouts/navbar' %>
<div class="edit-product-page">
    <h1>Editing Product</h1>
    <%= render 'form' %>
</div>

app/views/products/index.html.erb
<div class="all-products-page">
    <%= render 'layouts/navbar' %>

    <div class="all-products">
        <h2>All Products</h2>
        
        <% if logged_in? && current_user.isAdmin %>
            <%= link_to raw('<span class="fa fa-plus"></span> New Product'), new_product_path, class: 'btn btn-success' %>
        <% end %>
        
        <div class="all-products-content">
            <table class="table table-condensed">
                <%= render @products %>
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('tr.product-row').click(function() {
            $(this).next('tr.product-row-detail').find('div').slideToggle(300);
        });
        $('tr.product-row-detail').click(function() {
            $(this).find('div').slideUp(300);
        });
        $('a.btn').click(function(e) {
            e.stopPropagation();
        });
        $('td.product-action-delete button.btn-danger').click(function(e) {
            e.stopPropagation();
            $($(this).attr('data-target')).modal('show');
        });
    });
</script>

app/views/products/new.html.erb
<%= render 'layouts/navbar' %>

<div class="new-product-page">
    <h1>New Product</h1>
    
    <div class="new-product-content">
        <%= render 'form' %>
    </div>
</div>

app/views/products/show.html.erb
<div class="product-detail-page">
    <%= render 'layouts/navbar' %>

    <div class="product">
        <h2><%= @product.name %></h2>
        <%= link_to 'Edit', edit_product_path(@product) %>
        <hr/>
        
        <div class="product-info">
            <div class="product-image col-sm-3">
                <img src="../images/products/<%= @product.image %>"/>
            </div>
            
            <div class="product-description col-sm-6">
                <h4>Product Info</h4>
                <%= @product.description %>
            </div>
            
            <div class="product-pricing col-sm-3">
                <h3><%= '$' + @product.price.to_s %></h3>
                
                <!-- Add to Cart button -->
                <% if logged_in? %>
                    <!-- Logged in -->
                    <% if !current_user.has_item_in_cart(@product.id) %>
                        <!-- Item not yet in cart -->
                        <button type="button" class="btn btn-primary btn-add-to-cart"
                                data-toggle="modal" data-target="#product-cart-modal">
                                <span class="fa fa-shopping-cart fa-lg"></span>
                                <span>Add to Cart</span>
                        </button>
                        <div id="product-cart-modal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">
                                            <span class="fa fa-close"/>
                                        </button>
                                        <h4 class="modal-title">Add to Cart</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>Choose the quantity of (<%= @product.name %>) you'd like to purchase.</p>
                                        <table>
                                            <tr>
                                                <td class="modal-quantity"><input id="quantity-input" type="number" value="1" min="1"/></td>
                                                <td class="modal-times"><span class="fa fa-times fa-lg"></span></td>
                                                <td class="modal-unit-price"><span>$<%= @product.price %></span></td>
                                                <td class="modal-equals"><span class="fa fa-arrow-right fa-lg"></span></td>
                                                <td class="modal-total-price"><span class="product-cart-modal-total">$<%= @product.price %></span></td>
                                            </tr>
                                        </table>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">
                                            <span class="fa fa-close"/> Cancel
                                        </button>
                                        <%= link_to raw(
                                                        '<span class="fa fa-shopping-cart fa-lg"></span>
                                                        <span>Confirm</span>'
                                                    ),
                                                    {
                                                        :controller => "shopping_cart_items",
                                                        :action => "create",
                                                        :user_id => current_user.id,
                                                        :product_id => @product.id,
                                                        :quantity => 1
                                                    },
                                                    :method => 'post',
                                                    :class => 'btn btn-success btn-add-to-cart' %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <% else %>
                        <!-- Item already in cart -->
                        <a class="btn btn-primary btn-add-to-cart disabled">
                            <span class="fa fa-shopping-cart fa-lg"></span>
                            <span>Item in Cart</span>
                        </a>
                    <% end %>
                    
                    <!-- Add to Favorites button -->
                    <% if !current_user.has_item_favorited(@product.id) %>
                        <%= link_to raw(
                                        '<span class="fa fa-heart fa-lg"></span> Add to Favorites'
                                    ),
                                    {
                                        :controller => 'user_product_favorites',
                                        :action => 'create',
                                        :user_id => current_user.id,
                                        :product_id => @product.id
                                    },
                                    :method => 'put',
                                    :class => 'btn btn-info btn-favorite' %>
                    <% else %>
                        <%= link_to raw(
                                        '<span class="fa fa-ban fa-lg"></span> Remove from Favorites'
                                    ),
                                    {
                                        :controller => 'user_product_favorites',
                                        :action => 'create',
                                        :user_id => current_user.id,
                                        :product_id => @product.id
                                    },
                                    :method => 'delete',
                                    :class => 'btn btn-info btn-favorite' %>
                    <% end %>
                <% else %>
                    <!-- Not logged in -->
                    <a class="btn btn-primary btn-add-to-cart-login disabled">
                        <span class="fa fa-user fa-lg"></span>
                        <span>Log in or sign up to buy</span>
                    </a>
                <% end %>
            </div>
            
            <div class="separator"/>
        </div>
        
        <hr/>

        <div class="product-reviews">
            <h2>Reviews</h2>
            <% if @product.reviews.any? %>
                <%= render @product.reviews %>
            <% else %>
                There aren't any reviews for this product yet.
            <% end %>
        </div>

        <div class="product-add-review">
            <h2>Add a review</h2>
            
            <% if logged_in? %>
                <%= render 'reviews/form' %>
            <% else %>
                <p>Please <%= link_to 'log in', login_path %> or <%= link_to 'sign up', signup_path %> to post a review of a product.</p>
            <% end %>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        
        // When the quantity in the 'add to cart' modal is updated...
        $('div#product-cart-modal div.modal-body input#quantity-input').change(function() {
            
            // Update the projected total price
            var total = $('span.product-cart-modal-total');
            var unitPrice = Number(<%= @product.price %>);
            var quantity = Number($(this).val());
            var totalPrice = (Math.round((unitPrice * quantity) * 100) / 100);
            total.html('$' + totalPrice.toFixed(2));
            
            if (!isNaN(quantity) && quantity > 0) {
                // Update the quantity parameter on the 'confirm' link
                var addCartLink = $('div.modal-footer a.btn-add-to-cart');
                var linkText = addCartLink.attr('href');
                var startIndex = (linkText.indexOf('&quantity=') + 10);
                var endIndex = linkText.indexOf('&user_id=');
                var updatedLink = (linkText.substring(0, startIndex) + quantity + linkText.substring(endIndex));
                addCartLink.attr('href', updatedLink);
                addCartLink.removeClass('disabled');
            } else {
                $('div.modal-footer a.btn-add-to-cart').addClass('disabled');
            }
        });
    });
</script>